from playwright.sync_api import sync_playwright

try:
    with sync_playwright() as play:
        browser=play.chromium.launch(headless=False)
        page=browser.new_page()
        page.goto('https://localhost:4200/')

        signin_element=page.wait_for_selector('#signin-button')
        signin_element.click()
        page.wait_for_timeout(1000)

        # xpath - Relative xpath '//'
        #Using attribute  - //tagname[@attributename = "value"]
        username_element=page.wait_for_selector('//input[@name="Username"]')
        username_element.type('testuser')
        password_element=page.wait_for_selector('//input[@name="Password"]')
        password_element.type('Pass123$')
        login_element=page.wait_for_selector('//button[@name="button"]')
        login_element.click()
        page.wait_for_timeout(5000)

        setup_selector=page.wait_for_selector('//div[text()=" Setup "]')
        broker_selector=page.wait_for_selector('//div[text()=" Brokers "]')
        add_broker_selector=page.wait_for_selector('//mat-icon[text()="add"]')
        add_broker_selector.click()
        add_name_selector=page.wait_for_selector('//span[@text()="Name:"]')
        add_name_selector.select_option(label='Home broker')
        add_code_selector=page.wait_for_selector('//span[@text="Code:"]')
        add_code_selector.select_option(label='HOME')
        add_phone_selector=page.wait_for_selector('//span[@text="Phone Number:"]')
        add_phone_selector.select_option(label='+2567291019773')
        add_email_selector=page.wait_for_selector('//span[@text="Email:"]')
        add_email_selector.select_option(label='test@gmail.com')
        add_registration_date_selector=page.wait_for_selector('//span[@text="Registration Date:"]')
        add_registration_date_selector.select_option(label='2020-02-02')
        add_notes_selector=page.wait_for_selector('//span[@text="Notes:"]')
        add_notes_selector.select_option(label='Testing')
        save_broker_selector=page.wait_for_selector('//mat-icon[text()="save"]')
        save_broker_selector.click()
        page.wait_for_timeout(5000)
        refresh_broker_selector=page.wait_for_selector('//mat-icon[text()="refresh"]')
        refresh_broker_selector.click()
        page.wait_for_timeout(1000)
        search_broker_selector=page.wait_for_selector('//input[@placeholder="search..."]')
        search_broker_selector.type('Home broker')
        page.wait_for_timeout(1000)
        active_checkbox_selector=page.wait_for_selector('//input[@name="active"]')
        active_checkbox_selector.click()
        approve_checkbox_selector=page.wait_for_selector('//input[@name="approved"]')
        approve_checkbox_selector.click()
        add_br_cashaccountdetails_selector=page.wait_for_selector('//span[@text=" Add Cash Account "]')
        add_br_cashaccountdetails_selector.click()
        add_br_cashaccount_name_selector=page.wait_for_selector('//span[@text="Name:"]')
        add_br_cashaccount_name_selector.select_option(label='Home Cash Account')
        add_br_cashaccount_code_selector=page.wait_for_selector('//span[@text="Code:"]')
        add_br_cashaccount_code_selector.select_option(label='HCA')
        add_br_cashaccount_currency_selector=page.wait_for_selector('//span[@text="Currency:"]')
        add_br_cashaccount_currency_selector.select_option(label='United States dollar')
        add_br_bankBranch_selector=page.wait_for_selector('//span[@text="Bank Branch:"]')
        add_br_bankBranch_selector.select_option(label='Home Bank Branch')
        add_br_corebankingmode_selector=page.wait_for_selector('//span[@text="Core Banking Realtime Integration Mode:"]')
        add_br_corebankingmode_selector.select_option(label='NONE')
        add_br_accountnumber_selector=page.wait_for_selector('//span[@text="Account Number:"]')
        add_br_accountnumber_selector.select_option(label='1234567890')
        add_br_IBAN_selector=page.wait_for_selector('//span[@text="IBAN:"]')
        add_br_IBAN_selector.select_option(label='UG1234567890')
        add_br_notes_selector=page.wait_for_selector('//span[@text="Notes:"]')
        add_br_notes_selector.select_option(label='Testing')
        allowoverdrawing_checkbox_selector=page.wait_for_selector('//input[@name="allowOverdrawing"]')
        allowoverdrawing_checkbox_selector.click()
        save_broker_selector=page.wait_for_selector('//mat-icon[text()="save"]')
        save_broker_selector.click()
        page.wait_for_timeout(2000)
        search_br_account_selector=page.wait_for_selector('//input[@placeholder="search..."]')
        search_br_account_selector.type('Home Cash Account')
        page.wait_for_timeout(5000)
        doubleclick_broker_account_selector=page.wait_for_selector('//text="Home Cash Account"')
        doubleclick_broker_account_selector.dblclick()
        active_checkbox_selector=page.wait_for_selector('//input[@name="active"]')
        active_checkbox_selector.click()
        approve_checkbox_selector=page.wait_for_selector('//input[@name="approved"]')
        approve_checkbox_selector.click()
        save_br_accountdetails_selector=page.wait_for_selector('//mat-icon[text()="update"]')
        save_br_accountdetails_selector.click()
        save_broker_selector=page.wait_for_selector('//mat-icon[text()="update"]')
        save_broker_selector.click()

except:
    print('An error occurred')
finally:
    browser.close()
